FROM node:13.14-alpine

RUN mkdir -p /usr/src/
WORKDIR /usr/src

# COPY package.json /usr/src/
# COPY package-lock.json /usr/src/
# COPY index.ts /usr/src/
# COPY tsconfig.json /usr/src/

COPY / /usr/src

RUN npm install

CMD [ "npm", "start" ]
